# Generated by Django 4.1.7 on 2024-01-12 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0007_order_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'billing_charge_statuses',
            },
        ),
        migrations.CreateModel(
            name='PrepaidPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('original_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_rate', models.DecimalField(decimal_places=5, default=1, max_digits=7)),
                ('average_rate', models.DecimalField(decimal_places=5, default=1, max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(db_column='ccy_id', on_delete=django.db.models.deletion.RESTRICT, to='contracts.currency')),
            ],
            options={
                'db_table': 'billing_prepaid_packages',
            },
        ),
        migrations.CreateModel(
            name='PrepaidPackageCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateField()),
                ('charged_units', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_credit', models.BooleanField(default=False)),
                ('charge_status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='billing_module.chargestatus')),
                ('prepaid_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='billing_module.prepaidpackage')),
            ],
            options={
                'db_table': 'billing_package_charges',
            },
        ),
        migrations.CreateModel(
            name='OrderPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.order')),
                ('prepaid_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_module.prepaidpackage')),
            ],
            options={
                'db_table': 'billing_order_packages',
                'ordering': ['prepaid_package__start_date'],
            },
        ),
    ]
