# Generated by Django 4.1.7 on 2024-01-13 05:10

from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_order_end_date'),
        ('vendors', '0013_alter_vendorservice_unique_together'),
        ('services', '0002_alter_service_options'),
        ('billing_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpackages',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='contracts.order'),
        ),
        migrations.CreateModel(
            name='OrderCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', month.models.MonthField()),
                ('service_count', models.IntegerField()),
                ('charged_units', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='contracts.order')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contracts.paymenttype')),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.RESTRICT, related_name='charges', to='services.service')),
                ('vendor', models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.RESTRICT, related_name='charges', to='vendors.vendor')),
            ],
            options={
                'db_table': 'billing_order_charges',
            },
        ),
    ]
