# Generated by Django 4.1.7 on 2024-03-24 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_order_end_date'),
        ('billing_module', '0003_remove_prepaidpackage_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidpackage',
            name='contract',
            field=models.ForeignKey(db_column='contract_id', default=171, on_delete=django.db.models.deletion.RESTRICT, related_name='packages', to='contracts.contract'),
            preserve_default=False,
        ),
    ]
