# Generated by Django 4.1.7 on 2023-04-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileProcessingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('number_of_files', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
                ('processed_documents', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'celery_tasks_file_processing',
            },
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
