# Generated by Django 4.1.7 on 2023-04-28 12:40

import celery_tasks.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celery_tasks', '0002_fileprocessingtask_delete_taskstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprocessingtask',
            name='processed_documents',
            field=celery_tasks.models.ProcessedDocumentsList(blank=True, default=list, null=True),
        ),
    ]
