# Generated by Django 4.1.7 on 2023-12-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_tasks', '0003_alter_fileprocessingtask_processed_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileprocessingtask',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
