# Generated by Django 4.1.7 on 2023-02-18 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('services', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.client')),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccy_type', models.CharField(db_column='type', max_length=10)),
                ('ccy_short', models.CharField(blank=True, max_length=5, null=True)),
                ('ccy_long', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'pricing_types',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('valid_from', models.DateField()),
                ('valid_till', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('tu_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('ccy_type', models.ForeignKey(db_column='ccy_type', on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='contracts.currency')),
                ('contract', models.ForeignKey(db_column='contract_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='contracts.contract')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmt_type', models.CharField(db_column='type', max_length=30)),
                ('description', models.CharField(db_column='descr', max_length=100)),
            ],
            options={
                'db_table': 'payment_types',
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='contracts.order')),
                ('service', models.ForeignKey(db_column='vendor_service_id', on_delete=django.db.models.deletion.CASCADE, to='vendors.vendorservice')),
            ],
            options={
                'db_table': 'order_services',
            },
        ),
        migrations.CreateModel(
            name='OrderPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='contracts.order')),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'db_table': 'order_prices',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(db_column='payment_type', on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='contracts.paymenttype'),
        ),
    ]
