# Generated by Django 4.1.7 on 2023-02-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='valid_from',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='valid_till',
        ),
    ]
