# Generated by Django 4.1.7 on 2023-05-02 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_order_tu_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ('ccy_type',), 'verbose_name_plural': 'Currencies'},
        ),
    ]
