# Generated by Django 4.1.7 on 2023-05-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_currency_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='ccy_long',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='ccy_short',
        ),
        migrations.AddField(
            model_name='currency',
            name='ccy_real',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='ccy_virtual',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
