# Generated by Django 4.1.7 on 2023-11-22 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_alter_vendor_description'),
        ('contracts', '0005_remove_currency_ccy_long_remove_currency_ccy_short_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-is_active', '-start_date']},
        ),
        migrations.AlterModelOptions(
            name='orderprice',
            options={'ordering': ['order', 'service__service_order']},
        ),
        migrations.AlterField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(db_column='contract_id', on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='service',
            field=models.ForeignKey(db_column='vendor_service_id', on_delete=django.db.models.deletion.RESTRICT, to='vendors.vendorservice'),
        ),
    ]
