# Generated by Django 4.1.7 on 2023-02-18 15:16

from django.db import migrations, models
import django.db.models.deletion
import shared.models
import shared.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', shared.models.PeriodField(max_length=7, validators=[shared.utils.period_validator])),
                ('unit_count', models.IntegerField()),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.RESTRICT, related_name='usage_stats', to='services.service')),
                ('vendor', models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.RESTRICT, related_name='usage_stats', to='vendors.vendor')),
            ],
            options={
                'db_table': 'stats_usage',
            },
        ),
    ]
