# Generated by Django 4.1.7 on 2023-03-02 14:59

from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_iteco_name'),
        ('clients', '0002_alter_clientcountry_options_alter_industry_options'),
        ('stats', '0003_rename_uniqueusers_uniqueuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UquStatsPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', month.models.MonthField(unique=True)),
                ('cumulative', models.IntegerField()),
                ('month', models.IntegerField()),
            ],
            options={
                'db_table': 'stats_uqu_period',
            },
        ),
        migrations.CreateModel(
            name='UquStatsPeriodVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', month.models.MonthField(unique=True)),
                ('cumulative', models.IntegerField()),
                ('month', models.IntegerField()),
                ('vendor', models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.RESTRICT, related_name='uqu_stats', to='vendors.vendor')),
            ],
            options={
                'db_table': 'stats_uqu_period_vendor',
            },
        ),
        migrations.CreateModel(
            name='UquStatsPeriodClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', month.models.MonthField(unique=True)),
                ('cumulative', models.IntegerField()),
                ('month', models.IntegerField()),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.RESTRICT, related_name='uqu_stats', to='clients.client')),
            ],
            options={
                'db_table': 'stats_uqu_period_client',
            },
        ),
    ]
