# Generated by Django 4.1.7 on 2023-03-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_uqustatsperiod_uqustatsperiodvendor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uqustatsperiod',
            old_name='month',
            new_name='uqu_month',
        ),
        migrations.RenameField(
            model_name='uqustatsperiodclient',
            old_name='month',
            new_name='uqu_month',
        ),
        migrations.RenameField(
            model_name='uqustatsperiodvendor',
            old_name='month',
            new_name='uqu_month',
        ),
        migrations.AddField(
            model_name='uqustatsperiod',
            name='uqu_new',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uqustatsperiodclient',
            name='uqu_new',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uqustatsperiodvendor',
            name='uqu_new',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
