# Generated by Django 4.1.7 on 2023-03-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clientcountry_options_alter_industry_options'),
        ('stats', '0005_rename_month_uqustatsperiod_uqu_month_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uqustatsperiodclient',
            unique_together={('period', 'client')},
        ),
    ]
