# Generated by Django 4.1.7 on 2023-03-02 17:07

from django.db import migrations
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_iteco_name'),
        ('stats', '0006_alter_uqustatsperiodclient_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uqustatsperiodclient',
            name='period',
            field=month.models.MonthField(),
        ),
        migrations.AlterField(
            model_name='uqustatsperiodvendor',
            name='period',
            field=month.models.MonthField(),
        ),
        migrations.AlterUniqueTogether(
            name='uqustatsperiodvendor',
            unique_together={('period', 'vendor')},
        ),
    ]
