# Generated by Django 4.1.7 on 2023-04-24 16:35

from django.db import migrations
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_usagestats_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagestats',
            name='month',
            field=month.models.MonthField(),
        ),
    ]
