# Generated by Django 4.1.7 on 2023-04-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_alter_usagestats_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usagestats',
            name='period',
        ),
    ]
