# Generated by Django 4.1.7 on 2023-04-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_remove_usagestats_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usagestats',
            old_name='month',
            new_name='period',
        ),
    ]
