# Generated by Django 4.1.7 on 2023-05-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_rename_month_usagestats_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueuser',
            name='country',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='uniqueuser',
            name='user_id',
            field=models.CharField(max_length=30),
        ),
    ]
