# Generated by Django 4.1.7 on 2023-05-20 20:45

from django.db import migrations, models
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_uniqueuser_country_alter_uniqueuser_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UquStatsPeriodCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', month.models.MonthField()),
                ('country', models.CharField(max_length=5)),
                ('cumulative', models.IntegerField()),
                ('uqu_month', models.IntegerField()),
                ('uqu_new', models.IntegerField()),
            ],
            options={
                'db_table': 'stats_uqu_period_country',
                'unique_together': {('period', 'country')},
            },
        ),
    ]
