# Generated by Django 4.1.7 on 2023-03-17 17:43

from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0003_alter_order_tu_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepaidPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_units', models.IntegerField()),
                ('purchased_amount', models.DecimalField(decimal_places=5, default=0.0, max_digits=12)),
                ('transferred_units', models.IntegerField(default=0)),
                ('transferred_amount', models.DecimalField(decimal_places=5, default=0.0, max_digits=12)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.RESTRICT, related_name='packages', to='contracts.order')),
            ],
            options={
                'db_table': 'order_packages',
            },
        ),
        migrations.CreateModel(
            name='PackageUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', month.models.MonthField()),
                ('used_units', models.IntegerField()),
                ('package', models.ForeignKey(db_column='package_id', on_delete=django.db.models.deletion.RESTRICT, related_name='usage', to='packages.prepaidpackage')),
            ],
            options={
                'db_table': 'order_package_usage',
            },
        ),
    ]
