# Generated by Django 4.1.7 on 2024-03-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_packageusage_used_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepaidpackage',
            name='order',
        ),
        migrations.DeleteModel(
            name='PackageUsage',
        ),
        migrations.DeleteModel(
            name='PrepaidPackage',
        ),
    ]
