# Generated by Django 4.1.7 on 2023-03-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('service_order',)},
        ),
    ]
