# Generated by Django 4.1.7 on 2023-12-18 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_alter_vendor_description'),
        ('services', '0002_alter_service_options'),
    ]

    def move_vendor_filter_overrides(apps, schema_editor):
        VendorFilterOverride = apps.get_model('vendors', 'VendorFilterOverride')
        ServiceFilterOverride = apps.get_model('services', 'ServiceFilterOverride')

        # Copy data from VendorFilterOverride to ServiceFilterOverride
        for vendor_filter_override in VendorFilterOverride.objects.all():
            ServiceFilterOverride.objects.create(
                filter=vendor_filter_override.filter,
                service=vendor_filter_override.service,
                vendor=vendor_filter_override.vendor,
            )

    def delete_vendor_filter_override(apps, schema_editor):
        VendorFilterOverride = apps.get_model('vendors', 'VendorFilterOverride')
        VendorFilterOverride.objects.all().delete()

    operations = [
        migrations.CreateModel(
            name='ServiceFilterOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.ForeignKey(db_column='filter_id', on_delete=django.db.models.deletion.RESTRICT, related_name='filter_overrides', to='services.filter')),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, related_name='filter_overrides', to='services.service')),
                ('vendor', models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.CASCADE, related_name='filter_overrides', to='vendors.vendor')),
            ],
            options={
                'db_table': 'service_filters_overrides',
            },
        ),
        migrations.RunPython(move_vendor_filter_overrides, reverse_code=delete_vendor_filter_override),
    ]
