# Generated by Django 4.1.7 on 2023-03-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcountry',
            options={'ordering': ('country',), 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ('industry',), 'verbose_name_plural': 'Industries'},
        ),
    ]
