# Generated by Django 4.1.7 on 2023-05-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clientcountry_options_alter_industry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Client ID'),
        ),
    ]
