# Generated by Django 4.1.7 on 2023-02-18 14:50

from django.db import migrations, models
import django.db.models.deletion
import reports.models
import shared.models
import shared.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('include_details', models.BooleanField(default=True)),
                ('show_pids', models.BooleanField(default=False)),
                ('client', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reports',
                    to='clients.client'
                )),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='ReportLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'db_table': 'report_languages',
            },
        ),
        migrations.CreateModel(
            name='ReportSkipColumnConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skip_columns', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'report_skip_columns',
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'report_type',
            },
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', shared.models.PeriodField(max_length=7, validators=[shared.utils.period_validator])),
                ('file', models.FileField(max_length=255, upload_to=reports.models.content_report_file_filename)),
                ('report', models.ForeignKey(
                    db_column='report_id',
                    on_delete=django.db.models.deletion.RESTRICT,
                    related_name='report_files',
                    to='reports.report'
                )),
            ],
            options={
                'db_table': 'report_files',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='language',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='reports',
                to='reports.reportlanguage'
            ),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.ForeignKey(
                db_column='report_type',
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='reports',
                to='reports.reporttype'
            ),
        ),
        migrations.AddField(
            model_name='report',
            name='skip_columns',
            field=models.ForeignKey(
                db_column='skip_columns',
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='reports',
                to='reports.reportskipcolumnconfig'
            ),
        ),
        migrations.AddField(
            model_name='report',
            name='vendors',
            field=models.ManyToManyField(db_table='report_vendors', related_name='reports', to='vendors.vendor'),
        ),
    ]
