# Generated by Django 4.1.7 on 2023-03-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportskipcolumnconfig_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
                ('default_folder', models.CharField(max_length=20, unique=True)),
                ('default_name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
    ]
