# Generated by Django 4.1.7 on 2023-03-03 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportfiletype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reportfiletype',
            table='report_file_types',
        ),
    ]
