# Generated by Django 4.1.7 on 2023-03-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_reportfiletype_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfiletype',
            name='default_folder',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reportfiletype',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
