# Generated by Django 4.1.7 on 2023-03-03 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_reportfiletype_default_folder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportfiletype',
            old_name='type',
            new_name='description',
        ),
        migrations.AddField(
            model_name='reportfile',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='report_files', to='reports.reportfiletype'),
            preserve_default=False,
        ),
    ]
