# Generated by Django 4.1.7 on 2023-03-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_rename_type_reportfiletype_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('status_type', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'transaction_statuses',
            },
        ),
    ]
