# Generated by Django 4.1.7 on 2023-04-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_reportfile_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfile',
            name='period',
        ),
    ]
