# Generated by Django 4.1.7 on 2023-04-24 16:41

from django.db import migrations
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_remove_reportfile_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='month',
            field=month.models.MonthField(),
        ),
    ]
