# Generated by Django 4.1.7 on 2023-04-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_reportfile_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportfile',
            old_name='month',
            new_name='period',
        ),
    ]
