# Generated by Django 4.1.7 on 2023-04-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_rename_month_reportfile_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportskipcolumnconfig',
            name='skip_columns',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
