# Generated by Django 4.1.7 on 2023-05-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_alter_reportskipcolumnconfig_skip_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionstatus',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
