# Generated by Django 4.1.7 on 2023-12-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_alter_transactionstatus_description'),
        ('stats', '0014_transactionstatus_usagetransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionStatus',
        ),
    ]
