# Generated by Django 4.1.7 on 2023-02-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinputfile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
