# Generated by Django 4.1.7 on 2023-03-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_iteco_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorservice',
            options={'ordering': ('service__service_order',)},
        ),
    ]
