# Generated by Django 4.1.7 on 2023-03-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_vendorservice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
