# Generated by Django 4.1.7 on 2023-04-08 13:56

from django.db import migrations, models
import django.db.models.deletion
import shared.models
import shared.utils


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options'),
        ('vendors', '0005_vendor_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', shared.models.PeriodField(max_length=7, validators=[shared.utils.period_validator])),
                ('unit_count', models.IntegerField()),
                ('service', models.ForeignKey(
                    db_column='service_id',
                    on_delete=django.db.models.deletion.RESTRICT,
                    related_name='vendor_usage',
                    to='services.service'
                )),
                ('vendor', models.ForeignKey(
                    db_column='vendor_id',
                    on_delete=django.db.models.deletion.RESTRICT,
                    related_name='vendor_usage',
                    to='vendors.vendor'
                )),
            ],
            options={
                'db_table': 'vendor_usage',
            },
        ),
    ]
