# Generated by Django 4.1.7 on 2023-04-24 16:12

from django.db import migrations
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendorusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinputfile',
            name='month',
            field=month.models.MonthField(null=True),
        ),
        migrations.AddField(
            model_name='vendorusage',
            name='month',
            field=month.models.MonthField(null=True),
        ),
    ]
