# Generated by Django 4.1.7 on 2023-04-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_vendorinputfile_month_vendorusage_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorinputfile',
            name='period',
        ),
        migrations.RemoveField(
            model_name='vendorusage',
            name='period',
        ),
    ]
