# Generated by Django 4.1.7 on 2023-04-24 16:28

from django.db import migrations
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_remove_vendorinputfile_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinputfile',
            name='month',
            field=month.models.MonthField(),
        ),
        migrations.AlterField(
            model_name='vendorusage',
            name='month',
            field=month.models.MonthField(),
        ),
    ]
