# Generated by Django 4.1.7 on 2023-04-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_rename_month_vendorusage_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorinputfile',
            old_name='month',
            new_name='period',
        ),
    ]
