# Generated by Django 4.1.7 on 2023-12-28 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options'),
        ('vendors', '0012_alter_vendor_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendorservice',
            unique_together={('vendor', 'service')},
        ),
    ]
